# Generated by Django 5.0.7 on 2025-04-11 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('mentor', '0003_rename_qualification_mentorprofile_current_role_and_more'),
        ('students', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_projects', to='college.collegeprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_projects', to='mentor.mentorprofile'),
        ),
    ]
