# Generated by Django 5.0.7 on 2025-04-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_alter_mentorprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorprofile',
            old_name='qualification',
            new_name='current_role',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='expertise_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_profiles/'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='teaching_branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
